### ISSUE TITLE
we are happy with this repo , from this we will learning new concepts with xv6  

### ISSUE THREAD

**Issue by mohanchgit** [tetsuyaAnkur/Date-in-xv6#1]
**please update  in the documentation section  [SYS_date] sys_date in place of [SYS_getyear] sys_date**

![update](https://user-images.githubusercontent.com/17300324/92765515-07932200-f3b3-11ea-858d-16110def3578.PNG)

**Comment by tetsuyaAnkur** [comment]
Thanks for pointing out. I have made the necessary changes.
